name: node-goat-ci-npm-docker

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitlab-ci*'
      - 'azure-pipelines*'
      - '.github/workflows/frogbot*'
      - '.github/workflows/jfrog-sast*'
  pull_request:
    types: 
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read #Ability to read the contents permission
  security-events: write # Required for uploading code scanning 

env:
  NODE_DEFAULT_VERSION: 20  
  NPM_JF_RT_REPO: ${{ vars.NPM_JF_RT_REPO }}
  DOCKER_JF_RT_REPO: ${{ vars.DOCKER_JF_RT_REPO }}
  JF_URL: ${{ vars.JF_URL }}
jobs:
  npm-docker-build-and-publish-dev:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "The job was triggered by a ${{ github.event_name }} event."
      - name: Check out repository code ðŸ›Žï¸
        uses: actions/checkout@v3
      - run: |
          echo "${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ env.NODE_DEFAULT_VERSION }}
      - name: JFrog CLI setup ðŸ¸
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}/
          JF_PROJECT: ${{ vars.JF_PROJECT }}
        with:
          oidc-provider-name: jf-github-rk 
          oidc-audience: https://github.com/rkfrog
      - name: Health check JFrog Artifactory instance ðŸ¸
        run: |
          jf --version
          jf rt ping
          jf config show
      - name: Set JF NPM Config
        run:  |
          jf npm-config --repo-deploy=$NPM_JF_RT_REPO -repo-resolve=$NPM_JF_RT_REPO
          jf npm config set registry ${{ env.JF_URL }}/artifactory/api/npm/$NPM_JF_RT_REPO/
          jf npm config list | jq -r .registry
        env:
          JF_URL: https://${{ vars.JF_URL }}
      - name: JFrog Curation audit ðŸ¸
        run: |
          jf curation-audit --threads 6
      - name: JFrog audit Secrets ðŸ”‘ðŸ¸
        run: |
          jf audit --secrets --validate-secrets true
      - name: JFrog audit - SAST ðŸ¸
        run: |
          jf audit --sast --format=sarif --fail false > jfrog_sast.sarif
      - name: Upload output to generate autofix
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: jfrog_sast.sarif
      - name: Capture build version
        run: |
          echo NPM_PACKAGE_BUILD_VERSION=$(cat package.json | jq -r ."version") >> $GITHUB_ENV
          echo NPM_PACKAGE_NAME=$(cat package.json | jq -r ."name") >> $GITHUB_ENV
      - name: Install NPM dependencies
        run: |
          jf npm ci --ignore-scripts --module npm-build
      - name: NPM publish ðŸ¸
        run: jfrog npm publish --module npm-build
      - name: Evidence Publish for NPM ðŸ¸
        run: |
          echo '{ "actor": "${{ github.actor }}", "date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'" }' > sign_npm.json
          jf evd create \
            --package-name ${{ env.NPM_PACKAGE_NAME }} \
            --package-version ${{ env.NPM_PACKAGE_BUILD_VERSION }} \
            --package-repo-name $NPM_JF_RT_REPO  \
            --key "${{ secrets.JF_EVD_PRIVATE_KEY }}"  --key-alias evidence-signing-rk \
            --predicate ./sign_npm.json --predicate-type https://jfrog.com/evidence/signature/v1 
          echo 'ðŸ”Ž NPM build Evidence attached: `signature` ðŸ” ' >> $GITHUB_STEP_SUMMARY
      - name: Login to JFrog Docker repo
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.JF_URL }}
          username: ${{ secrets.JF_USERNAME }}
          password: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: Docker Build ðŸ³ðŸ¸
        run: |
          echo "registry=https://${{ env.JF_URL }}/artifactory/api/npm/$NPM_JF_RT_REPO/" >> $HOME/.npmrc
          echo "//${{ env.JF_URL }}/artifactory/api/npm/$NPM_JF_RT_REPO/:_authToken=${{ env.NPM_TOKEN }}" >> $HOME/.npmrc
          jf docker image build --tag ${{ env.JF_URL }}/$DOCKER_JF_RT_REPO/node-goat:${{ env.NPM_PACKAGE_BUILD_VERSION }} --secret id=npmrc,src=$HOME/.npmrc --module docker-build  --build-arg="REGISTRY_URL=${{ env.JF_URL }}" --build-arg="DOCKER_REPO_NAME=$DOCKER_JF_RT_REPO" --build-arg="NPM_REPO_NAME=$NPM_JF_RT_REPO" .
        env:
          JF_URL: ${{ vars.JF_URL }}
          NPM_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      # - name: JFrog docker image scan ðŸ³ðŸ¸
      #   run: |
      #     jf docker scan ${{ env.JF_URL }}/$DOCKER_JF_RT_REPO/node-goat:${{ env.NPM_PACKAGE_BUILD_VERSION }} --format json --threads 6
      #   env:
      #     JF_URL: ${{ vars.JF_URL }}
      - name: Docker Push ðŸ³ðŸ¸
        run: |
          jf docker push ${{ env.JF_URL }}/$DOCKER_JF_RT_REPO/node-goat:${{ env.NPM_PACKAGE_BUILD_VERSION }} --module docker-build 
        env:
          JF_URL: ${{ vars.JF_URL }}
      - name: Evidence Publish for Docker ðŸ³ðŸ¸
        run: |
          echo '{ "actor": "${{ github.actor }}", "date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'" }' > sign_docker.json
          jf evd create \
            --package-name node-goat \
            --package-version ${{ env.NPM_PACKAGE_BUILD_VERSION }} \
            --package-repo-name $DOCKER_JF_RT_REPO  \
            --key "${{ secrets.JF_EVD_PRIVATE_KEY }}"  --key-alias evidence-signing-rk \
            --predicate ./sign_docker.json --predicate-type https://jfrog.com/evidence/signature/v1 
          echo 'ðŸ”Ž Docker build evidence attached: `signature` ðŸ” ' >> $GITHUB_STEP_SUMMARY
      - name: Gather build details ðŸ¸
        run: |
          jf rt build-add-git ./
          jf rt build-collect-env
      - name: JFrog build publish ðŸ¸
        run: jf rt build-publish
      - name: Sign Build Evidence ðŸ¸
        run: |
          echo '{ "actor": "${{ github.actor }}", "date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'" }' > sign_build.json
          jf evd create \
            --predicate ./sign_build.json --predicate-type https://jfrog.com/evidence/build-signature/v1 \
            --build-name ${{ env.JFROG_CLI_BUILD_NAME }} \
            --build-number ${{ env.JFROG_CLI_BUILD_NUMBER }} \
            --project ${{ vars.JF_PROJECT }} \
            --key "${{ secrets.JF_EVD_PRIVATE_KEY }}"  --key-alias evidence-signing-rk  
          echo 'ðŸ”Ž Build Evidence attached: `build-signature` ðŸ” ' >> $GITHUB_STEP_SUMMARY
      - name: JFrog build scan ðŸ¸
        run: |
          sleep 60
          jf build-scan --format json
      - name: JFrog create release bundle ðŸ¸
        run: |
          jf release-bundle-create --spec=rbv2_build_spec.json --spec-vars="build-name=${{ env.JFROG_CLI_BUILD_NAME }};build-number=${{ env.JFROG_CLI_BUILD_NUMBER }};project-key=${{ vars.JF_PROJECT }}" --sync=true --signing-key=${{ secrets.JF_RB_SIGNING_KEY_NAME }} ${{ env.JFROG_CLI_BUILD_NAME }} ${{ env.NPM_PACKAGE_BUILD_VERSION }}
      - name: Sign Release Bundle Evidence ðŸ¸
        run: |
          echo '{ "actor": "${{ github.actor }}", "date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'" }' > sign_rb.json
          jf evd create \
            --predicate ./sign_rb.json --predicate-type https://jfrog.com/evidence/build-signature/v1 \
            --release-bundle  ${{ env.JFROG_CLI_BUILD_NAME }} \
            --release-bundle-version ${{ env.NPM_PACKAGE_BUILD_VERSION }} \
            --project ${{ vars.JF_PROJECT }} \
            --key "${{ secrets.JF_EVD_PRIVATE_KEY }}"  --key-alias evidence-signing-rk  
          echo 'ðŸ”Ž Release Bundle Evidence attached: `release-bundle-signature` ðŸ” ' >> $GITHUB_STEP_SUMMARY